### ISSUE TITLE
Question: Are lines 25-32 necessary for Coverage

### ISSUE THREAD

**Issue by awentzel** [paambaati/websight#77]
I noticed in `https://github.com/paambaati/websight/blob/3e64f8d7b048aa5d4639c3c455e96ca7979d46c3/.github/workflows/ci.yml#L33-L49` that lines 25-32 are also included in `coverage` section of the yaml file. 

This would duplicate parts of the process.  A couple questions:
1. Can we omit duplicative steps?
2. Can we just omit the testing and collect coverage reports in the case they have already ran by `lerna run test` for example.
3. Is it possible to break out the notify code climate, collect coverage, sum-coverage, and upload-coverage in separate distinct steps for better logging?

**Comment by paambaati** [comment]
@awentzel They're just shown as a complete example only for reference. The relevant lines are only [L45 - L49](https://github.com/paambaati/websight/blob/3e64f8d7b048aa5d4639c3c455e96ca7979d46c3/.github/workflows/ci.yml#L45-L49).

**Comment by paambaati** [comment]
Closing this, as this isn't an issue related to this repo. @awentzel You can still use https://github.com/paambaati/codeclimate-action/issues/153.
