### ISSUE TITLE
CC_TEST_REPORTER_ID exposued

### ISSUE THREAD

**Issue by maximveksler** [paambaati/websight#82]
Hi, I was looking at your code for some stuff. I see you the coverage token exposed. 

I'd recommend you read it from github secrets instead of having it committed in code, as it's a clear security risk.

See here for more info https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by paambaati** [comment]
@maximveksler Thanks for pointing this out, I've rotated the keys and moved them to secrets.
